### ISSUE TITLE
Please add the rest of the boxes for python do_cleanup

### ISSUE THREAD

**Issue by atefganm** [Hains/openpli-dreambox-oe-core#10]
https://github.com/Hains/openpli-dreambox-oe-core/blob/main/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bb#L56

**Comment by fairbird** [comment]
Done
https://github.com/Hains/openpli-dreambox-oe-core/commit/b5806450b8ee87bdb0c64674815d97234c42b004

**Comment by atefganm** [comment]
ERROR

`Build Configuration:
BB_VERSION           = "1.51.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "11.1"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
BOX_BRAND            = "dreambox"
STB_PLATFORM         = "dm3gen"
SOC_FAMILY           = "bcm7435"
KERNELVERSION        = "3.4"
RCNAME               = "dmm2"
DISTRO_FEED_URI      = "http://ganm/feeds/openpli-11.1"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:73d5cd5e8d9d8a922b6a8a9d90adf0470a99314e"
meta                 = "HEAD:a6cc842973f8e3d5a72e6f4012d0430777901408"
meta-python2         = "HEAD:8db9e4f6ceae33d7a4f55453d31e69f9858af4eb"
meta-openpli         
meta-dreambox        
meta-kodi            = "main:17f695d74ae4573cc8a0920a6222520a985168f9"

Initialising tasks: 100% |####################################################################################################################################################################################################| Time: 0:00:05
Sstate summary: Wanted 329 Local 307 Network 0 Missed 22 Current 1777 (93% match, 98% complete)
Removing 13 stale sstate objects for arch dm820: 100% |#######################################################################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 56
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 57
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 58
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 59
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 60
WARNING: python should use 4 spaces indentation, but found tabs in enigma2-plugin-extensions-openwebif.bb, line 61
ERROR: Task (/home/atef/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bb:do_package) failed with exit code '134' 
Pseudo log:
Setup complete, sending SIGUSR1 to pid 23037.
path mismatch [2 links]: ino 19838409 db '/home/atef/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugin-extensions-openwebif/gitAUTOINC+ad6fe58c28-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/public/images/boxes/arivalink200.jpg' req '/home/atef/openpli-dreambox-oe-core/build/tmp/work/dm820-oe-linux/enigma2-plugin-extensions-openwebif/gitAUTOINC+ad6fe58c28-r0/packages-split/enigma2-plugin-extensions-openwebif/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif'.

NOTE: Tasks Summary: Attempted 6387 tasks of which 6294 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bb:do_package
Summary: There were 60 WARNING messages shown.
make: *** [Makefile:107: image] Error 1
atef@ganm:~/openpli-dreambox-oe-core$ 
`

**Comment by fairbird** [comment]
Try now ...

**Comment by atefganm** [comment]
More than 10 minutes and it's stopped like this . . . . 

![Screenshot_2021-07-10_21-32-45](https://user-images.githubusercontent.com/31848885/125174629-05fadc00-e1c7-11eb-99d2-8852485cbe47.png)

**Comment by atefganm** [comment]
**Looks like I need to reinstall the operating system again**

`atef@ganm:~/openpli-dreambox-oe-core$ MACHINE=dm820 make image
Building image for dm820
Loading cache: 100% |                                                                                                                                                                                                        | ETA:  --:--:--
Loaded 0 entries from dependency cache.
ERROR: ExpansionError during parsing /home/atef/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-youtube-dl.bb###################################                              | ETA:  0:00:25
Traceback (most recent call last):
  File "/home/atef/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1175, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7fa951fb8490>, d=<bb.data_smart.DataSmart object at 0x7fa9520a0130>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/atef/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1584, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7fa951fb8490>, d=<bb.data_smart.DataSmart object at 0x7fa9520a0130>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/atef/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 694, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7fa951fb8490>, d=<bb.data_smart.DataSmart object at 0x7fa9520a0130>, name='default'):
             """
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/atef/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 683, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7fa951fb8490>, d=<bb.data_smart.DataSmart object at 0x7fa9520a0130>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/atef/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 892, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1477"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python-native:/home/atef/openpli-dreambox-oe-core/openembedded-core/scripts:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/atef/openpli-dreambox-oe-core/bitbake/bin:/home/atef/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/atef"; git -c core.fsyncobjectfiles=0 ls-remote https://github.com/ytdl-org/youtube-dl.git ', d=<bb.data_smart.DataSmart object at 0x7fa952066a00>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1477"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python-native:/home/atef/openpli-dreambox-oe-core/openembedded-core/scripts:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/atef/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-youtube-dl/2_fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/atef/openpli-dreambox-oe-core/bitbake/bin:/home/atef/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/atef"; git -c core.fsyncobjectfiles=0 ls-remote https://github.com/ytdl-org/youtube-dl.git  failed with exit code 128, output:
fatal: unable to access 'https://github.com/ytdl-org/youtube-dl.git/': GnuTLS recv error (-54): Error in the pull function.



Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:107: image] Error 1
atef@ganm:~/openpli-dreambox-oe-core$`

**Comment by fairbird** [comment]
I think you need to clean your ubuntu or do new install...
AS you see in my build log the compile and build done just fine ...

> raed@fairbird:~/build_image/Us-OpenPLI/openpli-dreambox-oe-core$ make image
Building image for 
Loading cache: 100% |######################################################################################################################| Time: 0:00:00
Loaded 4519 entries from dependency cache.
Parsing recipes: 100% |####################################################################################################################| Time: 0:00:34
Parsing of 3238 .bb files complete (2941 cached, 297 parsed). 4816 targets, 379 skipped, 0 masked, 0 errors.
Removing 1 recipes from the allarch sysroot: 100% |########################################################################################| Time: 0:00:00
Removing 2 recipes from the cortexa15hf-neon-vfpv4 sysroot: 100% |#########################################################################| Time: 0:00:00
Removing 3 recipes from the dm920 sysroot: 100% |##########################################################################################| Time: 0:00:00
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.51.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "dm920"
DISTRO               = "openpli"
DISTRO_VERSION       = "11.1"
TUNE_FEATURES        = "arm vfp cortexa15 neon vfpv4 callconvention-hard"
TARGET_FPU           = "hard"
BOX_BRAND            = "dreambox"
STB_PLATFORM         = "dm4kgen"
SOC_FAMILY           = "bcm7252s"
KERNELVERSION        = "3.14"
DISPLAY_TYPE         = "    colorlcd400 "
RCNAME               = "dmm2"
DISTRO_FEED_URI      = "http://fairbird/feeds/openpli-11.1"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:73d5cd5e8d9d8a922b6a8a9d90adf0470a99314e"
meta                 = "HEAD:a6cc842973f8e3d5a72e6f4012d0430777901408"
meta-python2         = "HEAD:8db9e4f6ceae33d7a4f55453d31e69f9858af4eb"
meta-openpli         
meta-dreambox        
meta-kodi            = "main:98668da9e83ff8cf7918de8607d122507e61d4bc"

Initialising tasks: 100% |#################################################################################################################| Time: 0:00:09
Sstate summary: Wanted 356 Local 302 Network 0 Missed 54 Current 1758 (84% match, 97% complete)
Removing 10 stale sstate objects for arch dm920: 100% |####################################################################################| Time: 0:00:00
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 6467 tasks of which 6312 didn't need to be rerun and all succeeded.
raed@fairbird:~/build_image/Us-OpenPLI/openpli-dreambox-oe-core$

**Comment by atefganm** [comment]
Parsing recipes: 100% |#######################################################################################################################################################################################################| Time: 0:02:30
Parsing of 3238 .bb files complete (0 cached, 3238 parsed). 4816 targets, 403 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.51.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "dm820"
DISTRO               = "openpli"
DISTRO_VERSION       = "11.1"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
BOX_BRAND            = "dreambox"
STB_PLATFORM         = "dm3gen"
SOC_FAMILY           = "bcm7435"
KERNELVERSION        = "3.4"
RCNAME               = "dmm2"
DISTRO_FEED_URI      = "http://ganm/feeds/openpli-11.1"
meta-oe              
meta-filesystems     
meta-multimedia      
meta-networking      
meta-python          = "HEAD:73d5cd5e8d9d8a922b6a8a9d90adf0470a99314e"
meta                 = "HEAD:a6cc842973f8e3d5a72e6f4012d0430777901408"
meta-python2         = "HEAD:8db9e4f6ceae33d7a4f55453d31e69f9858af4eb"
meta-openpli         
meta-dreambox        
meta-kodi            = "main:98668da9e83ff8cf7918de8607d122507e61d4bc"

Initialising tasks: 100% |####################################################################################################################################################################################################| Time: 0:00:20
Sstate summary: Wanted 2106 Local 0 Network 0 Missed 2106 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 6437 tasks of which 0 didn't need to be rerun and all succeeded.
atef@ganm:~/openpli-dreambox-oe-core$
