### ISSUE TITLE
Please Add  classes/gittag.bbclass  

### ISSUE THREAD

**Issue by atefganm** [Hains/openpli-dreambox-oe-core#15]
Please Add  classes/gittag.bbclass  

atef@atef:~/openpli-dreambox-oe-core$ MACHINE=dm820 make image
Building image for dm820
Loading cache: 100% |###############################################################################################################################################################################| Time: 0:00:00
Loaded 88 entries from dependency cache.
ERROR: ParseError at /home/atef/openpli-dreambox-oe-core/meta-openpli/recipes-devtools/python/streamlink-27.bb:30: Could not inherit file classes/gittag.bbclass                                    | ETA:  0:01:00

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:107: image] Error 1
atef@atef:~/openpli-dreambox-oe-core$

**Comment by atefganm** [comment]
https://github.com/oe-alliance/oe-alliance-core/blob/4.4/meta-oe/classes/gittag.bbclass

**Comment by fairbird** [comment]
https://github.com/Hains/openpli-dreambox-oe-core/commit/5fd0b178ea59590fe8c0aeecc85b7db80e421563
