### ISSUE TITLE
I want your source dreamTWO

### ISSUE THREAD

**Issue by hatak55** [Hains/openpli-dreambox-oe-core#2]
I want your source dreamTWO
And also the method, please

**Comment by Hains** [comment]
Hi,

Audio is not working AFAIK.
@fairbird  is it worth to add dreamone and two?

**Comment by fairbird** [comment]
Yes ... Please add it and will be keep it open to all .. May some friends in feature help us and push new commit to solve Audio .

**Comment by hatak55** [comment]
hy audio work for oe2.0 for pure2 and openpli8 jafar and  openatv ...work for all team

**Comment by fairbird** [comment]
Does not work correctly ... Japhar Team and Pure2 using same patches (And as you now it is close source) and openatv also built by Japhar Team ...

**Comment by hatak55** [comment]
What are the required commands for dreamTWO ?

**Comment by Hains** [comment]
MACHINE=dreamtwo make image

Work in progress. 
Even when it does build, audio is not working.
