### ISSUE TITLE
Please add a patch to Nodejs

### ISSUE THREAD

**Issue by atefganm** [Hains/openpli-dreambox-oe-core#8]
Please add a patch to Nodejs
https://github.com/OpenPLi/openpli-oe-core/tree/develop/meta-openpli/recipes-devtools/nodejs

**Comment by Hains** [comment]
https://github.com/Hains/openpli-dreambox-oe-core/commit/4ab69c455aa9c6f5cefa74b361032b3aa87b4ca2
